version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: "386"
      - goos: freebsd
        goarch: "386"
      - goos: openbsd
        goarch: "386"
    flags:
      - -trimpath
    ldflags:
      - >
        -s -w
        -X github.com/mishamyrt/ticketeer/internal/ticketeer.commitHash={{.Commit}}

archives:
  - format: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  use: git